### PR TITLE
ledger permit fix

### LINKED ISSUE #272: Cannot use ERC20Permit with Ledger device
**Describe the issue**
When trying to deposit through Tenderize with a token with `ERC20Permit` support (signature based token approvals) the app will throw an exception after signing with a Ledger device. 

image

This error indicates the *recovery id*  (v param) of the ECDSA signature is incorrect. 

The `v` value for an ECDSA signature in Ethereum should be `27` or `28` according to the Ethereum yellow paper (From [Ethereum's Yellow Paper](https://ethereum.github.io/yellowpaper/paper.pdf) Appendix F - Signing Transactions. The acceptable values for v are 27 or 28.)

However our ledger device seems to return either `0` or `1` for the parameter: `v value: 0`

**Potential solution**
Check if the `v` param from the signature returned from `signERC2612Permit` is either `0` or `1`, if it is hardcode it to be `27` instead. 

```javascript
      if (permit.v === 0 || permit.v === 1) permit.v = 27
```

### PR DESCRIPTION
**Pull request by vmaark**
fixes #272

### CODE REVIEW

File: packages/app/src/utils/signERC2612PermitPatch.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
+import { signERC2612Permit } from "eth-permit";
+
+type ERC2612Permit = Awaited<ReturnType<typeof signERC2612Permit>>;
+
+const patchPermit = (permit: ERC2612Permit) => {
+  return {
+    ...permit,
+    v: permit.v === 0 ? 27 : permit.v === 1 ? 28 : permit.v,
```
Comment (kyriediculous) [inline packages/app/src/utils/signERC2612PermitPatch.ts:8]:
```suggestion
    v: permit.v === 0 || v.permit === 1 ? permit.v + 27 : permit.v
```

File: packages/app/src/utils/signERC2612PermitPatch.ts [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+  provider: any,
+  token: string,
+  owner: string,
+  spender: string,
+  value?: string | number,
+  deadline?: number | undefined,
+  nonce?: number | undefined
+): Promise<ERC2612Permit> => {
+  const result = await signERC2612Permit(provider, token, owner, spender, value, deadline, nonce);
+  return patchPermit(result);
```
Comment (kyriediculous) [inline packages/app/src/utils/signERC2612PermitPatch.ts:22]: I'm generally not a fan of mutation. 

We could avoid a large diff here by having a helper that only takes in the current "v" value returned by signERC2612Permit and returns a fresh value which can then be used as a return value from the hook itself

**Review by kyriediculous — CHANGES_REQUESTED** [review]

File: packages/app/src/utils/signERC2612PermitPatch.ts (hunk 2 above)
Comment (vmaark) [reply packages/app/src/utils/signERC2612PermitPatch.ts:22]: otherwise we always have to patch it in every call site (every hook), in my opinion this is a safer solution to prevent regressions.

**Review by kyriediculous — APPROVED** [review]
