### PR TITLE
Fix bugs from Gnosis feedback

### LINKED ISSUE #290: Add liquidity button is not disabled when inputs are empty
Currently the add liquidity button is not disabled when the input fields are empty, allowing the user to click it and receive an error in the console. 

**solution**: disable button when no user inputs are there

image

### LINKED ISSUE #291: Approve Token button should be hidden when token is approved but user input is empty
Currently, all our actions that allow a user to deposit/stake/swap tokens that require an approval beforehand check whether the user input amount is smaller than the allowance, in which case the "Approve token" button is hidden. 

However when a user has an approval of N tokens but the input field isn't filled out this will still show the approve button. This confuses users to think their tokens are not approved. 

**Solution**: 

Also perform the approval check when the input field is empty. 
The check can be `input < allowance`. 

- if input is 0 and allowance > 0 --> don't show button
- if input is 0 and allowance 0 --> show button
- if input > allowance --> show button
- if input <= allowance --> don't show button button

### PR DESCRIPTION
**Pull request by kyriediculous**
- Fixes #291 : Hide "Approve Token" button when user has an allowance but the input field is still empty. From feedback this confuses users into thinking the token hasn't been approved yet. 

- Fixes #290 : The "Add Liquidity" button wasn't disabled when the form fields were empty allowing users to think they weren't required and giving an error in the console. 

- This PR doesn't fix the long wait time for a transaction to confirm through gnosis safe. After investigation we think it's because we wait until the transaction confirm through the gnosis safe provider which seem to take longer than other providers.

### CODE REVIEW

File: packages/app/src/components/approve/useIsTokenApproved.ts [hunk 1]
```diff
@@ -15,14 +15,15 @@ export const useIsTokenApproved = (
...
           method: "allowance",
           args: [ownerAddress, spenderAddress],
         }
     ) ?? {};
 
+    console.log(allowance)
+
   const amountWei = utils.parseEther(amount || "0");
-  return allowance?.[0].gte(amountWei) ?? false;
+  return allowance?.[0].gt(amountWei) ?? false
```
Comment (vmaark) [inline packages/app/src/components/approve/useIsTokenApproved.ts:28]: lint!

Comment (kyriediculous) [reply packages/app/src/components/approve/useIsTokenApproved.ts]: fixed and rebased

File: packages/app/src/components/approve/useIsTokenApproved.ts [hunk 2]
```diff
@@ -22,5 +22,9 @@ export const useIsTokenApproved = (
         }
     ) ?? {};
   const amountWei = utils.parseEther(amount || "0");
-  return allowance?.[0].gt(amountWei) ?? false;
+  const allowanceParsed: BigNumber = allowance?.[0] || constants.Zero
```
Comment (vmaark) [inline packages/app/src/components/approve/useIsTokenApproved.ts:25]: !format
Also explicit typing is not needed I think

**Review by vmaark — APPROVED** [review]
LGTM 👍

**Review by vmaark — APPROVED** [review]
👍
